[tool.poetry]
name = "travel-concierge"
version = "0.1.0"
description = "Orchestrates personalized travel experiences, illustrates means to integrate booking systems, and provides support throughout the traveler's journey, from initial planning, booking, to real-time itinerary services and alerts."
authors = [
    "Gary Ng <gkcng@google.com>",
    "Arun Santhanagopalan <asanthan@google.com>",
    "Renee Zhang <xiaolizhang@google.com>",
    "Anisha Kaul <anishasjkaul@google.com>",
    "Duncan Renfrow-Symon <drenfrowsymon@google.com>",
]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
google-cloud-aiplatform = { extras = [
    "adk",
    "agent-engines",
], version = "^1.93.0" }
pydantic = "^2.10.6"
python-dotenv = "^1.0.1"
google-genai = "^1.16.1"
google-adk = "^1.0.0"
arize-otel = { version = "^0.8.2", python = ">=3.11,<3.13" }
openinference-instrumentation-google-adk = { version = "^0.1.0", python = ">=3.11,<3.14" }
openinference-instrumentation = "^0.1.34"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
google-adk = { version = "^1.0.0", extras = ["eval"] }
pytest-asyncio = "^0.26.0"

[tool.poetry.group.deployment]
optional = true

[tool.poetry.group.deployment.dependencies]
absl-py = "^2.2.1"
cloudpickle = "^3.1.1"
flake8-pyproject = "^1.2.3"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
